pipeline { 
    agent {
        label 'agent1'
    }
     
    stages {
      stage("checkout scm") {
        steps {
          git branch: 'terraform', url: 'https://github.com/PriyeshPandey07/terraform-pipeline-vpc-subnet.git'
        }
      }

      stage("terraform Init"){
        steps { 
            sh 'terraform init'
        }
      }

      stage("terraform plan"){
        steps {
            sh 'terraform plan'
        }
      } 

      stage("terraform apply") { 
        steps { 
            sh 'terraform apply --auto-approve'
        }
      }
      
      #stage("terraform destroy") { 
        #steps { 
            #sh 'terraform destroy --auto-approve'
        }
      }
    }
}
